//
//  NSString+Annex.h
//  Annex
//
//  Created by Wess Cope on 2/20/13.
//  Copyright (c) 2013 Wess Cope. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface NSString (Annex)
@property (readonly, nonatomic) NSString *camelCaseString;
@property (readonly, nonatomic) NSString *underscoreString;

/**
 `NSString(Annex)` is an extension to NSString with additional functionality.
 */

/**
 Exact reverse of -isEqualToString
 
 @param String	The string to compare to
 @return BOOL	if string is not equal to aString.
 */
- (BOOL)isNotEqualToString:(NSString *)aString;

/**
 Checks to see if string is equal to aString using case insensitive option (n == N)

 @param String	The string to compare to
 @return BOOL	if string is equal to aString
 */
- (BOOL)isEqualToStringCaseInsensitive:(NSString *)aString;

/**
 Checks to see if string is equal to aString using diacritic insenstive option (ñ == n)
 
 @param String	The string to compare to
 @return BOOL	if string is equal to aString
 */
- (BOOL)isEqualToStringDiacriticallyInsensitive:(NSString *)aString;

/**
 Creates an MD5 Hash from the current string.
 
 @return MD5 Hash created from current string.
 */
- (NSString *)md5;

/**
 Creates an SHA1 Hash from the current string.
 
 @return SHA1 Hash created from current string.
 */
- (NSString *)sha1;

/**
 Encodes string for safe use with URLs
 
 @return String that has been URL encoded.
 */
- (NSString *)URLEncoded;

/**
 Strips HTML from string.
 
 @return String with no HTML tags
 */
- (NSString *)stringByRemovingHTML;

/**
 Creates an MD5 Hash from a given string.
 
 @param string  The string to create MD5 hash from.
 @return        MD5 Hash created from current string.
 */
+ (NSString *)md5HashWithString:(NSString *)string;

/**
 Creates an SHA1 Hash from a given string.
 
 @param string  The string to create SHA1 hash from.
 @return        SHA1 Hash created from current string.
 */
+ (NSString *)sha1HashWithString:(NSString *)string;

/**
 Encodes the given string to be URL safe/friendly.
 
 @param string  The string to URL encode.
 @return        URL encoded string.
 */
+ (NSString *)urlEncodedStringWithString:(NSString *)string;

/**
 Returns a string generated by NSUUID with RFC 4122 version 4 random bytes ("E621E1F8-C36C-495A-93FC-0C247A3E6E5F")
 
 @return    String created by the system.
 */
+ (NSString *)UUIDString;

/**
 Returns an NSUUID if the receiver a valid UUID string such as "E621E1F8-C36C-495A-93FC-0C247A3E6E5F". Returns nil for invalid strings.
 
 @return    NSUUID created by the system.
 */
- (NSUUID *)UUIDRepresentation;

/**
 Converts an NSDate to a string with a given format.
 
 @param date    The date to convert to a string
 @param format  The format to convert the date to.
 @return            String created from date using format.
 */
+ (NSString *)stringFromDate:(NSDate *)date withFormat:(NSString *)format;

/**
 Converts an NSDate to a string with a given format.
 
 @param date        The date to convert to a string
 @param format      The format to convert the date to.
 @param timeZone    Timezone used when converting date to string.
 @return            String created from date using format.
 */
+ (NSString *)stringFromDate:(NSDate *)date withFormat:(NSString *)format withTimeZone:(NSTimeZone *)timeZone;

@end

@interface NSString (DeprecatedMethods)

/**
 Retreives a system universal id.
 
 @return    String created by the system.
 */
+ (NSString *)uuid __deprecated_msg("Use [NSString UUIDString] instead");

@end
